// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Swagger.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class BasketResponse
    {
        /// <summary>
        /// Initializes a new instance of the BasketResponse class.
        /// </summary>
        public BasketResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the BasketResponse class.
        /// </summary>
        public BasketResponse(string basketId = default(string), System.Guid? customerId = default(System.Guid?), double? totalPrice = default(double?), int? totalItems = default(int?), IList<BasketItemResponse> items = default(IList<BasketItemResponse>))
        {
            BasketId = basketId;
            CustomerId = customerId;
            TotalPrice = totalPrice;
            TotalItems = totalItems;
            Items = items;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "basketId")]
        public string BasketId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "customerId")]
        public System.Guid? CustomerId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "totalPrice")]
        public double? TotalPrice { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "totalItems")]
        public int? TotalItems { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "items")]
        public IList<BasketItemResponse> Items { get; set; }

    }
}
