// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Swagger.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CreateBasketRequest
    {
        /// <summary>
        /// Initializes a new instance of the CreateBasketRequest class.
        /// </summary>
        public CreateBasketRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CreateBasketRequest class.
        /// </summary>
        public CreateBasketRequest(System.Guid? customerId = default(System.Guid?))
        {
            CustomerId = customerId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "customerId")]
        public System.Guid? CustomerId { get; set; }

    }
}
